### ISSUE TITLE
early-return extension for end of surrounding block

### ISSUE THREAD

**Issue by mdelah** [mgechev/revive#1133]
The `early-return` rule finds opportunities to reduce nesting by inverting the condition of an `if` statement. Presently it can make suggestions for code like

```
func foo() {
    if cond { // suggests: if ! cond { return }
       bar()
       baz()
    } else {
        return
    }
}
```
and
```
for {
    if cond { // suggests: if ! cond { continue }
       bar()
       baz()
    } else {
        continue
    }
}
```
It doesn't have anything to say about the following conceptually equivalent code:

```
func foo() {
    if cond { // could still suggest: if ! cond { return }
       bar()
       baz()
    }
}
```
or
```
for {
    if cond { // could still suggest: if ! cond { continue }
       bar()
       baz()
    }
}
```
Despite the lack of `else`, we can still reduce nesting in the above cases owing to being at the end of the surrounding `for` block or function body.

I think this would be a neat extension, and fairly simple to implement. Happy to put up a PR if the maintainers are okay with the concept.

Alternatively, I guess it could be done as a new, separate rule, or guarded behind a linter argument to preserve the existing behaviour by default.

**Comment by chavacava** [comment]
Hi @mdelah, thanks for the proposal.
Indeed, it's something it could be added to the rule. Even the suggested code does not reduces the overall nesting, it might help keeping the _happy path_ at minimum nesting. 
If implemented, IMO it should be activated by conf because the choice between
```go
for {
    if cond {
       bar()
       baz()
    }
}
```
and 
```go
for {
    if ! cond { 
       continue 
    }

    bar()
    baz()
}
```
is a question of _taste_.

Something that might be tricky is to determine which structured jump (`continue` or `return`) to propose.
