### ISSUE TITLE
unreachable-code rule has some flaws

### ISSUE THREAD

**Issue by Abirdcfly** [mgechev/revive#717]
I noticed that in some cases we give unreachable code incorrectly and in other cases we cannot detect unreable code.

Just pointing it out for others to see. If anyone wants to fix it, I'd appreciate it!

```go
package main

import (
	"os"
	os1 "os"
        "fmt"
)

func main() {
	A()
	B()
}

func A() int {
	os.Exit(1)
	panic("unreachable")  // report unreachable code wrong. some case in golang/tools 
}

func B() int {
	os1.Exit(1)
        fmt.Println("hello")  // The code here is not reachable, but not reported because we use import aliases 
	panic("unreachable")
}
```

**Comment by chavacava** [comment]
IMO both cases are unreachable code. There is no reason the `os.Exit(1)` in function `A` does not take the control out of the program ([actual example](https://go.dev/play/p/KYPPIDo4jxK)), thus spotting the next sentence as unreachable is not a false positive.

To spot the second case we could exploit the import [alias information in the AST](https://pkg.go.dev/go/ast#ImportSpec) and retrieve the actual imported package.

Notice that in your example there is another undetected case: in the main function, the call to `B` is unreachable because `A` exits. Detecting cases like that is not impossible but somewhat tricky

**Comment by Abirdcfly** [comment]
I agree with the other parts.

as for the first case, the `panic` acts as a `return` statement in many functions that require a return value, just so the compiler doesn't report an error.

in the case of the above example, if I delete the panic statement on `func A() int{}`, I get an error when compiling`. /main.go:17:1: missing return`.

**Comment by chavacava** [comment]
> in the case of the above example, if I delete the panic statement on func A() int{}, I get an error when compiling. /main.go:17:1: missing return.

Yes but it changes nothing to the unreachable nature of the statement thus it is difficult to argue the warn is a _false positive_. 

For the sake of comfort (i.e. to avoid adding a comment to deactivate the linter in that exact line) One thing we could do is to do not warn if the unreachable statement is exactly `panic("unreachable")`

**Comment by mgechev** [comment]
Can we close this issue accepting the flaws?
