### ISSUE TITLE
add package-naming setting rather var-naming 

### ISSUE THREAD

**Issue by awkj** [mgechev/revive#97]
**Is your feature request related to a problem? Please describe.**
a rule, rule.var-naming have two effect, packakge name lint and variable name lint, I want to set them in two rule.
**Describe the solution you'd like**
add [rule.package-naming] setting to lint 
https://github.com/mgechev/revive/blob/50f3790f328935116bf41b757869719dbd4635d7/rule/var-naming.go#L44

**Describe alternatives you've considered**
no

**Additional context**

**Comment by mgechev** [comment]
Related to our discussion at https://github.com/mgechev/revive/issues/46

**Comment by mgechev** [comment]
We're keeping the package-wide analysis out of scope for now to keep revive performant. Closing for now.

**Comment by ernestoalejo** [comment]
@mgechev Sorry but I think this issue is about splitting a rule that does two checks in two different rules so we can control them independently of each other. For example I want to lint the variable names but I also want to ignore `this_package_names` and right now I need to keep a custom fork to do that. I fail to see how keeping both checks in the same rule keeps revive more performant.

**Comment by adlion** [comment]
this is very frustrating

How to disable ignore `this_package_names` in revive?
var-name documentation does not show anything for it
I keep folders and files names with underscore and try to keep package names similar

**Comment by thiagomata** [comment]
You can use brute force by excluding the failing condition by regex.
```
  golangci-lint run --verbose \
  --exclude="\bexported \w+ (\S*['.]*)([a-zA-Z'.*]*) should have comment or be unexported\b" \
  --exclude="\bdon't use an underscore in package name\b"
```
